controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_controller:
  ros__parameters:
    front_left_wheel_command_joint_name:  front_left_wheel_joint
    front_right_wheel_command_joint_name: front_right_wheel_joint
    rear_left_wheel_command_joint_name:   rear_left_wheel_joint
    rear_right_wheel_command_joint_name:  rear_right_wheel_joint

    kinematics:
      wheels_radius: 0.05
      wheels_separation_width: 0.361
      wheels_separation_length: 0.314
      sum_of_robot_center_projection_on_X_Y_axis: 0.3375

      base_frame_offset:
        x: 0.0
        y: 0.0
        theta: 0.0

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    use_stamped_vel: false
    reference_timeout: 0.5
    wheel_axis: z

    command_interfaces:
      - linear/x
      - linear/y
      - angular/z



    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.03]
